<?php
interface Interface_Database_Query{
	/**
	 * @param string sql statement name
	 * @return Interface_Database_Query
	 */
	public function call($function);

	/**
	 * takes any number of parameters
	 * @return Interface_Database_Query
	 */
	public function withParameters(/*...*/);

	/**
	 * gets exactly one value from the query and closes ste query
	 * @return mixed
	 */
	 public function fetchSingleValue();

	 /**
	  * provide an array for the results
	  * @return Interface_Database_Query
	  */
	 public function useResultArray(&$array);

	 /**
	  * fetches the next line in the result array
	  * use this if you have provided a custom array via useResultArray()
	  * @return void
	  */
	 public function fetch();

	 /**
	  * fetches the next line in the result array and returns it
	  * @return array
	  */
	 public function fetchResult();

	 /**
	  * returns the lines affected by this query
	  * @return int
	  */
	 public function getAffectedRows();

	 /**
	  * returns the last insert id generated by this query
	  * @return int
	  */
	 public function getInsertID();

	 /**
	  * clean up
	  */
	 public function close();
}

?>
