CREATE TABLE IF NOT EXISTS  Managers(
  managerID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  manager varchar(64) UNIQUE NOT NULL
)ENGINE = MYISAM CHARACTER SET utf8 COLLATE utf8_unicode_ci;
		
CREATE TABLE IF NOT EXISTS ContentIndex(
  contentID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  managerREL INTEGER NOT NULL,
  managerContentID varchar(32) UNIQUE NOT NULL,
  title TEXT NOT NULL,
  pubDate INTEGER,
  summary TEXT
)ENGINE = MYISAM CHARACTER SET utf8 COLLATE utf8_unicode_ci;
		
CREATE TABLE IF NOT EXISTS Changes(
  changeID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  contentREL INTEGER NOT NULL,
  title varchar(255) NOT NULL,
  size INTEGER,
  changeDate INTEGER NOT NULL,
  username varchar(64) NOT NULL
)ENGINE = MYISAM CHARACTER SET utf8 COLLATE utf8_unicode_ci;
		
CREATE TABLE IF NOT EXISTS Tags(
  tagID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  tag varchar(64) UNIQUE NOT NULL,
  blocked INTEGER
)ENGINE = MYISAM CHARACTER SET utf8 COLLATE utf8_unicode_ci;
		
CREATE TABLE IF NOT EXISTS Aliases(
  aliasID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  alias varchar(128) UNIQUE NOT NULL,
  active INTEGER,
  contentREL INTEGER NOT NULL
)ENGINE = MYISAM CHARACTER SET utf8 COLLATE utf8_unicode_ci;
		
CREATE TABLE IF NOT EXISTS relContentTags(
  contentREL INTEGER NOT NULL,
  tagREL INTEGER NOT NULL
)ENGINE = MYISAM CHARACTER SET utf8 COLLATE utf8_unicode_ci;