-- save and set charset, colation, default table engine
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, 
	UNIQUE_CHECKS=0;
	
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, 
	FOREIGN_KEY_CHECKS=0;
	
SET @OLD_SQL_MODE=@@SQL_MODE, 
	SQL_MODE='TRADITIONAL';
		
-- charset
SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT, 
	CHARACTER_SET_CLIENT='utf8';
		
SET @OLD_CHARACTER_SET_CONNECTION=@@CHARACTER_SET_CONNECTION, 
	CHARACTER_SET_CONNECTION='utf8';
		
SET @OLD_CHARACTER_SET_DATABASE=@@CHARACTER_SET_DATABASE, 
	CHARACTER_SET_DATABASE='utf8';
		
SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS, 
	CHARACTER_SET_RESULTS='utf8';
		
SET @OLD_CHARACTER_SET_SERVER=@@CHARACTER_SET_SERVER, 
	CHARACTER_SET_SERVER='utf8';
	
-- collation
SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION, 
	COLLATION_CONNECTION='utf8_unicode_ci';
			
SET @OLD_COLLATION_DATABASE=@@COLLATION_DATABASE, 
	COLLATION_DATABASE='utf8_unicode_ci';
			
SET @OLD_COLLATION_SERVER=@@COLLATION_SERVER, 
	COLLATION_SERVER='utf8_unicode_ci';
			
-- table format
SET @OLD_TABLE_TYPE=@@TABLE_TYPE, 
	TABLE_TYPE='InnoDB';
			
